# Generated by Django 5.1 on 2024-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
