# Generated by Django 5.1 on 2024-08-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_finalmodel_findimage_delete_productx'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='check2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_files', to='market.check2'),
        ),
    ]
