# Generated by Django 4.2.15 on 2024-08-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_check2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='check2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_files', to='market.check2'),
        ),
    ]
