# Generated by Django 4.2.15 on 2024-08-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_findimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findimage',
            name='image',
            field=models.ImageField(upload_to='final_images/'),
        ),
    ]
