# Generated by Django 4.2.15 on 2024-08-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_finalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='find_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
