# Generated by Django 4.2.15 on 2024-08-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_checkfile_productcheck_delete_productx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckFile',
        ),
    ]
