# Generated by Django 5.0.7 on 2024-08-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20240801_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductX',
            fields=[
                ('product_x_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='reversed_product_files/')),
                ('file_reg_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversed_files', to='marketplace.product')),
            ],
        ),
    ]
